# Generated by Django 3.2.13 on 2022-05-18 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_view', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='description',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='geeksmodel',
            name='title',
            field=models.CharField(max_length=25),
        ),
    ]
