# Generated by Django 3.2.13 on 2022-05-18 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('generic_view', '0002_auto_20220518_0612'),
    ]

    operations = [
        migrations.AlterField(
            model_name='geeksmodel',
            name='title',
            field=models.CharField(max_length=50),
        ),
    ]
