# Generated by Django 4.0.4 on 2022-04-21 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_title', models.CharField(max_length=250)),
                ('blog_desc', models.TextField()),
                ('blog_img', models.ImageField(upload_to='blog/images')),
                ('created_at', models.DateTimeField()),
            ],
        ),
    ]
