# Generated by Django 3.2.13 on 2022-04-26 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='eemail',
            new_name='email',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='econtact',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='eid',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='ename',
        ),
        migrations.AddField(
            model_name='employee',
            name='name',
            field=models.CharField(default='No Name', max_length=50),
        ),
        migrations.AddField(
            model_name='employee',
            name='phone',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
