# Generated by Django 3.2.13 on 2022-05-23 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('1', '1'), ('0', '0')], default='1', max_length=20),
        ),
    ]
