# Generated by Django 3.2.13 on 2022-05-23 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_team_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'De-active')], default='1', max_length=20),
        ),
    ]
