# Generated by Django 3.2.13 on 2022-05-05 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_employee_date_of_birth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='EmployeeTeam',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
