# Generated by Django 3.2.13 on 2022-04-28 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_employee_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='image',
            field=models.ImageField(blank=True, default='employee/NoImage.png', upload_to='employee/'),
        ),
    ]
