# Generated by Django 3.2.13 on 2022-05-05 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employeegroup_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='group',
            new_name='team',
        ),
        migrations.AlterField(
            model_name='employeeteam',
            name='status',
            field=models.CharField(choices=[('1', 'Active'), ('0', 'De-active')], default='1', max_length=20),
        ),
    ]
