# Generated by Django 3.2.13 on 2022-05-05 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20220505_1207'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeeteam',
            table='teams',
        ),
    ]
