# Generated by Django 3.2.13 on 2022-05-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_auto_20220502_0833'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeegroup',
            table='employee_group',
        ),
    ]
