# Generated by Django 3.2.13 on 2022-05-02 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employeegroup_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='employeegroup',
            table='employee_groups',
        ),
    ]
