# Generated by Django 3.2.13 on 2022-04-29 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employee_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='user',
        ),
    ]
