# Generated by Django 3.2.13 on 2022-04-27 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0004_destination_created_at_destination_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, upload_to='pics'),
        ),
    ]
