# Generated by Django 3.2.13 on 2022-04-27 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0007_alter_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(blank=True, default='settings.MEDIA_ROOT/pics/NoImage.jpg', upload_to='pics/'),
        ),
    ]
