# Generated by Django 3.2.13 on 2022-04-27 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travello', '0008_alter_destination_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='destination',
            name='image',
            field=models.ImageField(default='pics/NoImage.png', upload_to='pics/'),
        ),
    ]
