# Generated by Django 4.0.4 on 2022-04-29 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('cat_name', models.CharField(max_length=250)),
                ('cat_status', models.IntegerField(choices=[(1, 'Active'), (2, 'InActive'), (3, 'Deleted')], default='1')),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['cat_name'],
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('phone', models.CharField(max_length=250)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('blog_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_id', models.IntegerField(default='1')),
                ('blog_title', models.CharField(max_length=250)),
                ('blog_desc', models.TextField()),
                ('blog_img', models.ImageField(default='untitled.png', upload_to='blog/images')),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('blog_category', models.ManyToManyField(to='blog.category')),
            ],
            options={
                'ordering': ['blog_title'],
            },
        ),
    ]
