# Generated by Django 4.0.4 on 2022-04-22 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_blog_blog_img_alter_blog_blog_desc_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='user_id',
            field=models.IntegerField(default='1'),
        ),
    ]
