# Generated by Django 4.0.4 on 2022-05-05 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_tags_blog_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='is_published',
            field=models.IntegerField(default='0'),
        ),
    ]
