# Generated by Django 4.0.4 on 2022-04-29 13:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_options_alter_category_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='blog_category',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='blog.category'),
        ),
    ]
