# Generated by Django 4.0.4 on 2022-04-26 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_blog_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='blog_category',
            field=models.IntegerField(default='1'),
        ),
    ]
