# Generated by Django 4.0.4 on 2022-04-26 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blog_blog_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='id',
        ),
        migrations.AddField(
            model_name='blog',
            name='blog_id',
            field=models.BigAutoField(default='1', primary_key=True, serialize=False),
        ),
    ]
