# Generated by Django 4.0.4 on 2022-04-27 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_alter_contact_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='blog_id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
